export const LOGIN_MEMBER = 'LOGIN_MEMBER'
export const LOGOUT_MEMBER = 'LOGOUT_MEMBER'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAN_CART = 'CLEAN_CART'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const PUT_DB = 'PUT_DB'


export const LOGIN_MEMBER_SAGA = 'LOGIN_MEMBER_SAGA'
export const LOGOUT_MEMBER_SAGA = 'LOGOUT_MEMBER_SAGA'
export const ADD_TO_CART_SAGA = 'ADD_TO_CART_SAGA'
export const REMOVE_FROM_CART_SAGA = 'REMOVE_FROM_CART_SAGA'